export type ApplicationStatus = "new" | "contacted" | "approved" | "declined"

export type InsuranceStatus = "has" | "none"
export type NoInsuranceAcknowledgment = "rentalcover" | "declined"

export interface ApplicationInsurance {
  status?: InsuranceStatus
  carrier?: string
  policyNumber?: string
  noInsuranceAcknowledgment?: NoInsuranceAcknowledgment
  decisionAt?: string
}

export function hasInsuranceProof(insurance: ApplicationInsurance | null | undefined) {
  return Boolean(insurance?.carrier && insurance?.policyNumber)
}

export function declinedInsurance(insurance: ApplicationInsurance | null | undefined) {
  return insurance?.status === "none" && insurance?.noInsuranceAcknowledgment === "declined"
}

/** Whether a carrier + policy number still need to be collected before this
 * application can be approved. Only gates renters who chose to buy
 * short-term coverage through RentalCover.com before pickup and haven't
 * provided that policy yet — renters who already have their own insurance,
 * or who explicitly declined coverage, can be approved without it. */
export function needsInsuranceProof(insurance: ApplicationInsurance | null | undefined) {
  const choseRentalCover =
    insurance?.status === "none" && insurance?.noInsuranceAcknowledgment === "rentalcover"
  return choseRentalCover && !hasInsuranceProof(insurance)
}

/** Human-readable summary of the renter's insurance choice, for the
 * application detail view and the booking confirmation email. */
export function describeInsuranceChoice(insurance: ApplicationInsurance | null | undefined): string {
  if (insurance?.status === "has") {
    return hasInsuranceProof(insurance)
      ? `${insurance.carrier} - Policy #${insurance.policyNumber}`
      : "Has own insurance (carrier and policy number pending)"
  }

  if (insurance?.status === "none") {
    if (insurance.noInsuranceAcknowledgment === "rentalcover") {
      return hasInsuranceProof(insurance)
        ? `Obtained short-term coverage through RentalCover.com: ${insurance.carrier} - Policy #${insurance.policyNumber}`
        : "No policy at booking — chose to get short-term coverage through RentalCover.com before pickup"
    }
    if (insurance.noInsuranceAcknowledgment === "declined") {
      return "Declined coverage — proceeding without insurance"
    }
    return "No insurance (response pending)"
  }

  return "Not indicated"
}

export const APPLICATION_STATUSES: ApplicationStatus[] = ["new", "contacted", "approved", "declined"]

export type ApplicationBucket = "needs-attention" | "in-progress" | "completed"

export function bucketForStatus(status: ApplicationStatus): ApplicationBucket {
  if (status === "new") return "needs-attention"
  if (status === "contacted") return "in-progress"
  return "completed"
}

/** Applications sitting in a non-terminal status longer than this are flagged as waiting. */
export const WAITING_THRESHOLD_HOURS = 48

export function isTerminalStatus(status: ApplicationStatus) {
  return status === "approved" || status === "declined"
}

export function getWaitingHours(referenceDate: string | null) {
  if (!referenceDate) return null
  const ms = Date.now() - new Date(referenceDate).getTime()
  if (Number.isNaN(ms) || ms < 0) return null
  return ms / (1000 * 60 * 60)
}

export interface ApplicationListItem {
  id: string
  status: ApplicationStatus
  submittedAt: string | null
  statusUpdatedAt: string | null
  renterName: string
  renterEmail: string
  renterPhone: string
  vehicleLabel: string | null
  startDate: string | null
  endDate: string | null
}

export interface StatusHistoryEntry {
  from: ApplicationStatus | null
  to: ApplicationStatus
  changedAt: string
  changedBy: string
}

export interface VehicleChangeEntry {
  changedAt: string
  changedBy: string
  reason: string
  previousVehicleLabel: string | null
  newVehicleLabel: string
  previousAgreementPdfUrl: string | null
}

export interface AgreementEmailEntry {
  sentAt: string
  sentBy: string
  sentTo: string
}

/** The agreement regenerated by the most recent vehicle change. Absent until
 * the first vehicle change happens — the original `agreement` is the frozen,
 * customer-signed record and is never overwritten by later changes. */
export interface CurrentAgreement {
  pdfUrl: string | null
  vehicleLabel: string | null
  generatedAt: string | null
}

export interface ApplicationDetail {
  id: string
  status: ApplicationStatus
  submittedAt: string | null
  statusUpdatedAt: string | null
  statusHistory: StatusHistoryEntry[]
  vehicleChangeHistory: VehicleChangeEntry[]
  agreementEmailHistory: AgreementEmailEntry[]
  renter: {
    fullName: string
    phone: string
    email: string
    address: {
      street: string
      city: string
      state: string
      zip: string
    }
  }
  license: {
    number: string
    state: string
    expiry: string
    fileUrl: string | null
    fileName: string | null
  }
  insurance: ApplicationInsurance
  rental: {
    purpose: string
    startDate: string
    startTime: string
    endDate: string
    endTime: string
    visitorTimeZone: string
    rentalRate: "day" | "week"
    paymentDueDay: string
    mileageAllowance: string
    additionalNotes?: string
  }
  selectedVehicle: {
    label: string
    color: string
    pricePerDay: number
    pricePerWeek: number
    selectedRate: "day" | "week"
    selectedRatePrice: number
    vehicleId: string | null
    vehicleImage: string | null
  } | null
  additionalDrivers: Array<{
    name: string
    licenseNumber: string
    licenseState: string
  }>
  ownerCompany: {
    id: string
    name: string
    notificationEmail: string
  } | null
  agreementAccepted: boolean
  agreement: {
    accepted: boolean
    acceptedAt: string | null
    renterSignature: string
    ownerSignature: string
    ownerSignedDate: string
    pdfUrl: string | null
    renderedHtml: string | null
    plainText: string | null
  }
  currentAgreement: CurrentAgreement | null
}
